[tool.poetry]
name = "cutout"
version = "0.1.0"
description = ""
authors = ["Joshua <jpri6587@sydney.edu.au>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
numpy = "^1.22.2"
matplotlib = "^3.5.1"
astropy = "^5.0.1"
astroquery = "^0.4.5"
pandas = "^1.4.1"
astroutils = {git = "https://github.com/joshoewahp/astroutils.git", rev = "main"}
click = "^8.0.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"

[tool.poetry.scripts]
ccutout = "cutout.cli.cutout:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
